Configuration/TypoScript/setup.txt
Unless otherwise flexformed should all news plugins preset to display "news only", see https://github.com/cyberhouse/eventnews/issues/8
=> "news only" save default setting

Documentation/NeedSupport/Index.rst
Since TYPO3 Dev Days 2016, github has been the recommended place to have repositories, so this pull request updates that.
I have not changed the issue tracker link, which currently points to forge.typo3.org. Maybe that should point to github too..?
=> Fix link to point github repository, not git.typo3.org

Classes/Hooks/AbstractDemandedRepository.php
If the start date is in the past AND the end date is in the future, the event is not shown in the list view.
To display all the current events (events over several days), you need to add the following code.
best regards, Stephan
=> Events with enddate in the future are missing in list view

Configuration/Flexforms/flexform_eventnews.xml, Resources/Private/Language/locallang.xlf
The value of the "no constraint" option in the flexforms config was empty and so the value was always set to the value configured in TS.
Now the "no constraint" option now has a defined value (=3) to override the default setting.
The default empty option is labeled as "Defined in TypoScript"
=> [BUGFIX] fix "no constraint" eventRestriction in flexforms

Configuration/TCA/Overrides/tx_news_domain_model_news.php
There is a trailing comma in the new fields string of method `addToAllTCATypes` that is unneccessary. It leads to a double comma in the final `showitem` string: `title, is_event, --palette--;;palette_event, ,--palette--;;paletteCore,teaser,`. Even if it doesn't break anything it should be removed.
=> Remove unneccessary comma in TCA configuration

Configuration/TCA/Overrides/tx_news_domain_model_news.php
The TCA setting ['ctrl']['requestUpdate'] was removed from table tx_news_domain_model_news. The column field(s) "" and "is_event" were updated and contain option "'onChange' => 'reload'" parallel to 'config' and 'label' section.
=> [TASK] TCA update from requestUpdate to onChange

Configuration/TCA/tx_eventnews_domain_model_location.php, Configuration/TCA/tx_eventnews_domain_model_organizer.php
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.5/Deprecation-78524-TCAOptionVersioning_followPagesRemoved.html
=> [TASK] Remove deprecated "versioning_followPages"

Configuration/TCA/Overrides/tx_news_domain_model_news.php
Since the bodytext field is not available under External and Internal link types, the event details tab is placed at the back of the list instead of the second tab, like a regular news item. Changing this to teaser will solve the problem, since this field is shown on all types.
=> Change position for adding of Event Details tab to teaser

Classes/ViewHelpers/CalendarViewHelper.php
The year was previously added in this commit (4316692) to fix #38 but got somehow removed again. Without it the day filter does not work.
=> [BUGFIX] Readd year to day array

Configuration/TCA/tx_eventnews_domain_model_location.php, Configuration/TCA/tx_eventnews_domain_model_organizer.php
Location and Organizer tables had the wrong hidden field TCA. This caused the label to disappear as seen on the screenshot:
Corrected this with the default hidden field found in typo3/cms-frontend
=> [BUGFIX] correct hidden field in organizer and location

Classes/Hooks/AbstractDemandedRepository.php
The isEvent constraint was added to other news tables like tx_news_domain_model_tags in the tag list view of the plugin. 
This adds a simple class comparison to prevent that.
=> [BUGFIX] Check type before adding constraint

Configuration/TCA/tx_eventnews_domain_model_location.php, ext_tables.sql
Only two decimal places is inaccurate, the locatation may be off by several hundred meters.
The drawback of this change is that lat and lng have to be entered with ".", the automatic replacement of "," by "." does not work.
Fixes #123.
=> [BUGFIX] Allow more than 2 decimal places for location lat and lng.

Classes/Backend/FormDataProvider/EventNewsRowInitializeNew.php
When creating a new event, it doesn't make sense that the datetime field is filled with the current time.
=> [TASK] Prevent datetime being set to current time

Configuration/TCA/Overrides/tx_news_domain_model_news.php
This fixes the location of the `bodytext` which is no longer inside the "Event Details" tab.
This works with any news type, regarless if it has bodytext field.
Resolves #134
=> Put event details tab before "media"

ext_emconf.php
This extension threw a warning if you wanted to install it via extension manager in the TYPO3 backend. This was, because the ext_emconf has old constraints in it. It didn't match the composer.json requirements.
Will fix #148
=> [TASK] Update ext_emconf to match current composer requirements

Classes/Domain/Model/Dto/Demand.php
PHP 8.1 is throwing a Warning "Trying to access array offset on value of type null" when $settings = NULL
=> Prevent PHP Warning on PHP 8.1

Classes/Hooks/AbstractDemandedRepository.php
When using the event restriction (Demand::setEventRestriction) in combination with overwritten News models extending the eventnews ones, the IsEvent check isn't applied. This is due to the additional check added in 32c5dc5dd7dcec521bd5cbd80a8ce4e1571f271a (v6.0.0), which does not account for subclasses.
We manually tested this change with `georgringer/eventnews:6.0.0`,  `georgringer/news:11.1.2 ` and `typo3/cms-core:v11.5.30`.
=> [BUGFIX] Event restriction is not applied to News subclasses

Classes/Hooks/AbstractDemandedRepository.php
I haven't used the IsEvent restriction in combination with an extended demand class yet, but as a developer extending eventnews I expect the IsEvent restriction to also be effective on subclasses of the eventnews Demand class.
I manually tested this change with georgringer/news:11.1.2 and typo3/cms-core:v11.5.30 by using `\GeorgRinger\Eventnews\Domain\Model\Dto\Demand` for the passing path (the one that applies the restriction) and a direct subclass of `\GeorgRinger\News\Domain\Model\Dto\NewsDemand` for the early-return path.
Resolves: #122
=> [BUGFIX] Event restriction is not applied to Demand subclasses

Configuration/Flexforms/flexform_eventnews.xml
Contrary to some instructions on the web, extending Flexform fields for version 11 does not include an additional definition of `<TCEforms></TCEforms>` within an element. See: https://docs.typo3.org/p/georgringer/news/11.1/en-us/Tutorials/ExtendNews/ExtendFlexforms/Index.html
By removing this element, the flexform field will be displayed correctly again in the backend of TYPO3 v11.
=> Restoring the dropdown for "settings.eventRestriction" in the backend (v11)

Classes/Controller/NewsController.php
This change adds a fallback for the `categories` FlexForm field, which may be empty under rare circumstances.
=> [TASK] Prevent PHP warning if categories not available in FlexForm

ext_localconf.php
According to the documentation, the standard language is defined without specifying an additional key `default`.
See: https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Localization/ManagingTranslations.html#custom-translations
=> [BUGFIX] Fix locallangXMLOverride of default language

Classes/Controller/NewsController.php
@see https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
=> [TASK] Declare nullable types as nullable explicitly
